### ISSUE TITLE
Support GNU/Linux with Wine

### ISSUE THREAD

**Issue by CromFr** [nwn2dev/nwnx4#17]
Wine fails to inject the DLL into the nwn2server process. Some investigations are required :)

Some ideas:
- There may be something to configure on Linux or Wine to allow injecting code into the process
- Maybe detours is totally incompatible with wine and there better alternatives for Linux
- Maybe we could build nwnx4 for Linux and run only nwn2server with wine
- ...

**Comment by scottmunday84** [comment]
All valid possibilities. Detours is dependent on some Windows libraries, but you'd assume they'd be available to Wine.

**Comment by CromFr** [comment]
I did some quick tests and nwnx4 appears to work correctly on Wine (it loads the server, loads a big module and plugins appears to work). However I don't know if it is really reliable and if it can be used for a public server
